project_id: MY_PROJECT_ID
location: us-central1
app_id_manuals: SEARCH_APP_ID
app_id_safety_reports: OTHER_SEARCH_APP_ID
gcal_api_key: API_KEY
workshop_gcal_ID: 'ID@group.calendar.google.com'
janeDoe_gcal_ID: 'ID2@group.calendar.google.com'
johnSmith_gcal_ID: 'ID3@group.calendar.google.com'

